#!/usr/bin/env python3
"""Generate Every Day Greek course — 20 thematic lessons, ~100 words each."""
import json, os

# Each lesson: (theme_id, title, { category: [(term, lemma, english), ...] })
# term: display form e.g. "αγάπη,η" for nouns, plain lemma for verbs/adj/expr
# lemma: base form
# english: translation string

LESSONS = [
    (20, "Γεια! — Greetings & Daily Phrases", {
        "Εκφράσεις": [
            ("Γεια σου", None, "hi; hello; bye (informal singular)"),
            ("Γεια σας", None, "hello; goodbye (formal / plural)"),
            ("Γεια χαρά", None, "cheers; take care (casual farewell)"),
            ("Καλημέρα", None, "good morning"),
            ("Καλησπέρα", None, "good afternoon; good evening"),
            ("Καληνύχτα", None, "good night"),
            ("Αντίο", None, "goodbye"),
            ("Τα λέμε", None, "see you later; talk soon"),
            ("Εις το επανιδείν", None, "until we meet again (formal)"),
            ("Πώς είσαι;", None, "how are you? (informal)"),
            ("Πώς πάει;", None, "how's it going?"),
            ("Τι κάνεις;", None, "what are you doing?; how are you?"),
            ("Πολύ καλά", None, "very well"),
            ("Έτσι κι έτσι", None, "so-so"),
            ("Δεν παραπονιέμαι", None, "I can't complain"),
            ("Ευχαριστώ", None, "thank you"),
            ("Ευχαριστώ πολύ", None, "thank you very much"),
            ("Παρακαλώ", None, "please; you're welcome"),
            ("Συγγνώμη", None, "sorry; excuse me"),
            ("Δεν πειράζει", None, "it doesn't matter; no worries"),
            ("Εντάξει", None, "okay; alright"),
            ("Βεβαίως", None, "of course; certainly"),
            ("Φυσικά", None, "of course; naturally"),
            ("Με χαρά", None, "with pleasure; gladly"),
            ("Ορίστε", None, "here you are; pardon? (asking to repeat)"),
            ("Τι είπες;", None, "what did you say?"),
            ("Μπορείς να επαναλάβεις;", None, "can you repeat that?"),
            ("Με συγχωρείς", None, "excuse me (informal)"),
            ("Σε παρακαλώ", None, "please; I beg you (informal)"),
            ("Καλώς ήρθες", None, "welcome (singular)"),
            ("Καλώς ορίσατε", None, "welcome (formal/plural)"),
        ],
        "Ουσιαστικά": [
            ("πρωί,το", "πρωί", "morning"),
            ("απόγευμα,το", "απόγευμα", "afternoon"),
            ("βράδυ,το", "βράδυ", "evening"),
            ("νύχτα,η", "νύχτα", "night"),
            ("μέρα,η", "μέρα", "day"),
            ("χαρά,η", "χαρά", "joy; happiness; delight"),
            ("φίλος,ο", "φίλος", "friend (male)"),
            ("φίλη,η", "φίλη", "friend (female)"),
            ("κύριος,ο", "κύριος", "mister; sir; gentleman"),
            ("κυρία,η", "κυρία", "mrs; madam; lady"),
            ("όνομα,το", "όνομα", "name"),
            ("χαιρετισμός,ο", "χαιρετισμός", "greeting; salutation"),
        ],
        "Ρήματα": [
            ("λέω", None, "to say; to tell"),
            ("είμαι", None, "to be"),
            ("χαιρετώ", None, "to greet"),
            ("γνωρίζω", None, "to know; to meet (someone)"),
            ("παρουσιάζω", None, "to introduce; to present"),
            ("ρωτώ", None, "to ask"),
            ("απαντώ", None, "to answer; to reply"),
            ("μιλώ", None, "to speak; to talk"),
            ("ακούω", None, "to hear; to listen"),
            ("καταλαβαίνω", None, "to understand"),
            ("ξέρω", None, "to know"),
            ("χαίρομαι", None, "to be glad; pleased to meet you"),
            ("αποχαιρετώ", None, "to say goodbye"),
        ],
        "Επίθετα": [
            ("καλός/καλή/καλό", None, "good; fine"),
            ("ωραίος/ωραία/ωραίο", None, "beautiful; lovely; nice"),
            ("χαρούμενος/η/ο", None, "happy; cheerful"),
            ("ευγενικός/η/ό", None, "polite; kind; courteous"),
            ("ευχαριστημένος/η/ο", None, "pleased; satisfied"),
        ],
    }),

    (21, "Η Οικογένειά μου — Family & Relationships", {
        "Ουσιαστικά": [
            ("οικογένεια,η", "οικογένεια", "family"),
            ("σύζυγος,ο/η", "σύζυγος", "spouse; husband; wife"),
            ("άντρας,ο", "άντρας", "man; husband"),
            ("γυναίκα,η", "γυναίκα", "woman; wife"),
            ("παιδί,το", "παιδί", "child; kid"),
            ("κορίτσι,το", "κορίτσι", "girl"),
            ("αγόρι,το", "αγόρι", "boy"),
            ("γιος,ο", "γιος", "son"),
            ("κόρη,η", "κόρη", "daughter"),
            ("μαμά,η", "μαμά", "mom; mum"),
            ("μητέρα,η", "μητέρα", "mother"),
            ("μπαμπάς,ο", "μπαμπάς", "dad"),
            ("πατέρας,ο", "πατέρας", "father"),
            ("γιαγιά,η", "γιαγιά", "grandmother"),
            ("παππούς,ο", "παππούς", "grandfather"),
            ("αδερφός,ο", "αδερφός", "brother"),
            ("αδερφή,η", "αδερφή", "sister"),
            ("θείος,ο", "θείος", "uncle"),
            ("θεία,η", "θεία", "aunt"),
            ("ξάδερφος,ο", "ξάδερφος", "cousin (male)"),
            ("ξαδέρφη,η", "ξαδέρφη", "cousin (female)"),
            ("ανιψιός,ο", "ανιψιός", "nephew"),
            ("ανιψιά,η", "ανιψιά", "niece"),
            ("πεθερός,ο", "πεθερός", "father-in-law"),
            ("πεθερά,η", "πεθερά", "mother-in-law"),
            ("γαμπρός,ο", "γαμπρός", "son-in-law; brother-in-law; groom"),
            ("νύφη,η", "νύφη", "daughter-in-law; sister-in-law; bride"),
            ("σύντροφος,ο/η", "σύντροφος", "partner; companion"),
            ("αγαπημένος,ο", "αγαπημένος", "loved one; sweetheart"),
            ("μωρό,το", "μωρό", "baby"),
            ("νεογέννητο,το", "νεογέννητο", "newborn"),
            ("έγγονος,ο", "έγγονος", "grandson"),
            ("εγγονή,η", "εγγονή", "granddaughter"),
            ("συγγενής,ο/η", "συγγενής", "relative; kin"),
            ("γάμος,ο", "γάμος", "wedding; marriage"),
            ("διαζύγιο,το", "διαζύγιο", "divorce"),
            ("αρραβώνας,ο", "αρραβώνας", "engagement"),
        ],
        "Ρήματα": [
            ("αγαπώ", None, "to love"),
            ("φιλώ", None, "to kiss; to love"),
            ("αγκαλιάζω", None, "to hug; to embrace"),
            ("φροντίζω", None, "to take care of; to look after"),
            ("παντρεύομαι", None, "to marry; to get married"),
            ("χωρίζω", None, "to separate; to break up; to divorce"),
            ("γεννώ", None, "to give birth; to be born"),
            ("μεγαλώνω", None, "to grow up; to raise"),
            ("ανατρέφω", None, "to raise; to bring up"),
            ("στηρίζω", None, "to support; to back up"),
            ("προστατεύω", None, "to protect"),
            ("εμπιστεύομαι", None, "to trust"),
            ("ζηλεύω", None, "to be jealous; to envy"),
            ("υποστηρίζω", None, "to support; to stand by"),
        ],
        "Εκφράσεις": [
            ("Σ'αγαπώ", None, "I love you"),
            ("Σε φιλώ", None, "I kiss you; love (sign-off)"),
            ("Αγαπημένη μου", None, "my love; my darling (to female)"),
            ("Αγαπημένε μου", None, "my love; my darling (to male)"),
            ("Χαρά μου", None, "my joy; my dearest"),
            ("Ψυχή μου", None, "my soul; my darling"),
            ("Καλή οικογένεια", None, "a good family"),
            ("Είμαστε οικογένεια", None, "we are family"),
        ],
        "Επίθετα": [
            ("παντρεμένος/η/ο", None, "married"),
            ("ανύπαντρος/η/ο", None, "single; unmarried"),
            ("αρραβωνιασμένος/η/ο", None, "engaged"),
            ("χωρισμένος/η/ο", None, "separated; divorced"),
            ("μεγαλύτερος/η/ο", None, "older; bigger"),
            ("μικρότερος/η/ο", None, "younger; smaller"),
            ("μοναχοπαίδι,το", None, "only child"),
        ],
    }),

    (22, "Πώς νιώθω; — Feelings & Emotions", {
        "Ουσιαστικά": [
            ("συναίσθημα,το", "συναίσθημα", "feeling; emotion"),
            ("αγάπη,η", "αγάπη", "love; affection"),
            ("χαρά,η", "χαρά", "joy; happiness"),
            ("λύπη,η", "λύπη", "sadness; sorrow"),
            ("θυμός,ο", "θυμός", "anger"),
            ("φόβος,ο", "φόβος", "fear"),
            ("άγχος,το", "άγχος", "anxiety; stress; worry"),
            ("ανησυχία,η", "ανησυχία", "worry; concern; anxiety"),
            ("έκπληξη,η", "έκπληξη", "surprise"),
            ("ντροπή,η", "ντροπή", "shame; embarrassment"),
            ("ενοχή,η", "ενοχή", "guilt"),
            ("ζήλια,η", "ζήλια", "jealousy; envy"),
            ("αηδία,η", "αηδία", "disgust; repulsion"),
            ("πόνος,ο", "πόνος", "pain; ache; sorrow"),
            ("ελπίδα,η", "ελπίδα", "hope"),
            ("απόγνωση,η", "απόγνωση", "despair; hopelessness"),
            ("υπερηφάνεια,η", "υπερηφάνεια", "pride"),
            ("ντροπή,η", "ντροπή", "shame"),
            ("αγανάκτηση,η", "αγανάκτηση", "indignation; exasperation"),
            ("μοναξιά,η", "μοναξιά", "loneliness"),
            ("νοσταλγία,η", "νοσταλγία", "nostalgia; homesickness"),
            ("ανακούφιση,η", "ανακούφιση", "relief"),
            ("ευτυχία,η", "ευτυχία", "happiness; bliss"),
            ("δυστυχία,η", "δυστυχία", "unhappiness; misfortune"),
            ("περηφάνια,η", "περηφάνια", "pride"),
        ],
        "Ρήματα": [
            ("νιώθω", None, "to feel"),
            ("αισθάνομαι", None, "to feel; to sense"),
            ("χαίρομαι", None, "to be happy; to rejoice"),
            ("λυπάμαι", None, "to be sad; I'm sorry"),
            ("θυμώνω", None, "to get angry"),
            ("φοβάμαι", None, "to be afraid; to fear"),
            ("ανησυχώ", None, "to worry; to be anxious"),
            ("χαλαρώνω", None, "to relax"),
            ("στεναχωριέμαι", None, "to be upset; to worry"),
            ("ντρέπομαι", None, "to be ashamed; to be shy"),
            ("κλαίω", None, "to cry; to weep"),
            ("γελώ", None, "to laugh"),
            ("χαμογελώ", None, "to smile"),
            ("πονώ", None, "to hurt; to ache"),
            ("ελπίζω", None, "to hope"),
            ("απελπίζομαι", None, "to despair"),
            ("εκπλήσσομαι", None, "to be surprised"),
            ("απογοητεύομαι", None, "to be disappointed"),
            ("αγχώνομαι", None, "to be stressed; to get anxious"),
            ("ερωτεύομαι", None, "to fall in love"),
        ],
        "Επίθετα": [
            ("χαρούμενος/η/ο", None, "happy; cheerful"),
            ("λυπημένος/η/ο", None, "sad; unhappy"),
            ("θυμωμένος/η/ο", None, "angry; upset"),
            ("φοβισμένος/η/ο", None, "scared; frightened"),
            ("αγχωμένος/η/ο", None, "anxious; stressed"),
            ("χαλαρός/ή/ό", None, "relaxed; laid-back"),
            ("ενθουσιασμένος/η/ο", None, "enthusiastic; excited"),
            ("ανακουφισμένος/η/ο", None, "relieved"),
            ("περήφανος/η/ο", None, "proud"),
            ("ντροπαλός/ή/ό", None, "shy; bashful"),
            ("μοναχικός/ή/ό", None, "lonely; solitary"),
            ("ερωτευμένος/η/ο", None, "in love"),
            ("απογοητευμένος/η/ο", None, "disappointed"),
            ("συγκινημένος/η/ο", None, "moved; touched (emotionally)"),
            ("νευρικός/ή/ό", None, "nervous; irritable"),
            ("κουρασμένος/η/ο", None, "tired; exhausted"),
            ("εκνευρισμένος/η/ο", None, "irritated; annoyed"),
            ("τρομαγμένος/η/ο", None, "terrified; startled"),
            ("ευτυχισμένος/η/ο", None, "happy; blissful"),
            ("δυστυχισμένος/η/ο", None, "unhappy; miserable"),
        ],
        "Εκφράσεις": [
            ("Είμαι καλά", None, "I am well; I'm fine"),
            ("Δεν είμαι καλά", None, "I'm not well"),
            ("Με πιάνει άγχος", None, "I'm getting anxious; anxiety is gripping me"),
            ("Μου έρχεται να κλάψω", None, "I feel like crying"),
            ("Είμαι στα σύννεφα", None, "I'm on cloud nine; I'm daydreaming"),
            ("Μου φτιάχτηκε η διάθεση", None, "my mood improved; I cheered up"),
            ("Με τρώει από μέσα", None, "it's eating me up inside"),
            ("Ξεσπώ", None, "I'm venting; I'm blowing up"),
        ],
    }),

    (23, "Το Σπίτι μας — Home & Daily Life", {
        "Ουσιαστικά": [
            ("σπίτι,το", "σπίτι", "house; home"),
            ("διαμέρισμα,το", "διαμέρισμα", "apartment; flat"),
            ("σαλόνι,το", "σαλόνι", "living room; lounge"),
            ("κουζίνα,η", "κουζίνα", "kitchen"),
            ("υπνοδωμάτιο,το", "υπνοδωμάτιο", "bedroom"),
            ("μπάνιο,το", "μπάνιο", "bathroom"),
            ("τουαλέτα,η", "τουαλέτα", "toilet; WC"),
            ("είσοδος,η", "είσοδος", "entrance; hallway"),
            ("διάδρομος,ο", "διάδρομος", "corridor; hallway"),
            ("αυλή,η", "αυλή", "yard; courtyard"),
            ("μπαλκόνι,το", "μπαλκόνι", "balcony"),
            ("σκάλα,η", "σκάλα", "stairs; staircase; ladder"),
            ("πόρτα,η", "πόρτα", "door"),
            ("παράθυρο,το", "παράθυρο", "window"),
            ("πάτωμα,το", "πάτωμα", "floor"),
            ("ταβάνι,το", "ταβάνι", "ceiling"),
            ("τοίχος,ο", "τοίχος", "wall"),
            ("καναπές,ο", "καναπές", "sofa; couch"),
            ("τραπέζι,το", "τραπέζι", "table"),
            ("καρέκλα,η", "καρέκλα", "chair"),
            ("κρεβάτι,το", "κρεβάτι", "bed"),
            ("ντουλάπα,η", "ντουλάπα", "wardrobe; closet; cupboard"),
            ("ψυγείο,το", "ψυγείο", "refrigerator; fridge"),
            ("κουζινάκι,το", "κουζινάκι", "cooker; stove"),
            ("πλυντήριο,το", "πλυντήριο", "washing machine"),
            ("τηλεόραση,η", "τηλεόραση", "television; TV"),
            ("φωτιστικό,το", "φωτιστικό", "light; lamp"),
            ("κλειδί,το", "κλειδί", "key"),
            ("χαλί,το", "χαλί", "rug; carpet"),
            ("κουρτίνα,η", "κουρτίνα", "curtain"),
            ("καθρέφτης,ο", "καθρέφτης", "mirror"),
            ("ράφι,το", "ράφι", "shelf"),
            ("συρτάρι,το", "συρτάρι", "drawer"),
            ("μαξιλάρι,το", "μαξιλάρι", "pillow; cushion"),
            ("κουβέρτα,η", "κουβέρτα", "blanket"),
            ("σεντόνι,το", "σεντόνι", "sheet (bed)"),
            ("πετσέτα,η", "πετσέτα", "towel"),
            ("σαπούνι,το", "σαπούνι", "soap"),
            ("σαμπουάν,το", "σαμπουάν", "shampoo"),
            ("σκούπα,η", "σκούπα", "broom; vacuum cleaner"),
        ],
        "Ρήματα": [
            ("καθαρίζω", None, "to clean"),
            ("μαγειρεύω", None, "to cook"),
            ("τρώω", None, "to eat"),
            ("πίνω", None, "to drink"),
            ("κοιμάμαι", None, "to sleep"),
            ("ξυπνώ", None, "to wake up"),
            ("πλένω", None, "to wash"),
            ("σιδερώνω", None, "to iron"),
            ("τακτοποιώ", None, "to tidy up; to arrange"),
            ("κλειδώνω", None, "to lock"),
            ("ανοίγω", None, "to open"),
            ("κλείνω", None, "to close; to book"),
            ("σβήνω", None, "to turn off; to erase"),
            ("ανάβω", None, "to turn on; to light"),
            ("κατεβαίνω", None, "to go down; to come down"),
            ("ανεβαίνω", None, "to go up; to climb"),
            ("μένω", None, "to stay; to live (at a place)"),
        ],
        "Εκφράσεις": [
            ("Πήγαινε σπίτι", None, "go home"),
            ("Είμαι στο σπίτι", None, "I'm at home"),
            ("Στρώσε το τραπέζι", None, "set the table"),
            ("Μάζεψε τα παιχνίδια", None, "pick up the toys"),
            ("Βάλε τα στη θέση τους", None, "put them away; put them in their place"),
            ("Κάνε την κουζίνα", None, "do the kitchen; clean the kitchen"),
        ],
    }),

    (24, "Τρώμε! — Food & Eating", {
        "Ουσιαστικά": [
            ("φαγητό,το", "φαγητό", "food; meal"),
            ("φαΐ,το", "φαΐ", "food; grub (colloquial)"),
            ("γεύμα,το", "γεύμα", "meal; lunch (formal)"),
            ("πρωινό,το", "πρωινό", "breakfast"),
            ("μεσημεριανό,το", "μεσημεριανό", "lunch"),
            ("βραδινό,το", "βραδινό", "dinner; supper"),
            ("σνακ,το", "σνακ", "snack"),
            ("ψωμί,το", "ψωμί", "bread"),
            ("τυρί,το", "τυρί", "cheese"),
            ("φέτα,η", "φέτα", "feta (cheese)"),
            ("αυγό,το", "αυγό", "egg"),
            ("γιαούρτι,το", "γιαούρτι", "yoghurt"),
            ("μέλι,το", "μέλι", "honey"),
            ("ελιά,η", "ελιά", "olive"),
            ("λάδι,το", "λάδι", "oil; olive oil"),
            ("κρέας,το", "κρέας", "meat"),
            ("κοτόπουλο,το", "κοτόπουλο", "chicken"),
            ("ψάρι,το", "ψάρι", "fish"),
            ("χοιρινό,το", "χοιρινό", "pork"),
            ("αρνί,το", "αρνί", "lamb"),
            ("λαχανικό,το", "λαχανικό", "vegetable"),
            ("φρούτο,το", "φρούτο", "fruit"),
            ("πατάτα,η", "πατάτα", "potato"),
            ("ντομάτα,η", "ντομάτα", "tomato"),
            ("αγγούρι,το", "αγγούρι", "cucumber"),
            ("σαλάτα,η", "σαλάτα", "salad"),
            ("σούπα,η", "σούπα", "soup"),
            ("μακαρόνια,τα", "μακαρόνια", "pasta; macaroni"),
            ("ρύζι,το", "ρύζι", "rice"),
            ("νερό,το", "νερό", "water"),
            ("καφές,ο", "καφές", "coffee"),
            ("τσάι,το", "τσάι", "tea"),
            ("χυμός,ο", "χυμός", "juice"),
            ("γάλα,το", "γάλα", "milk"),
            ("κρασί,το", "κρασί", "wine"),
            ("μπύρα,η", "μπύρα", "beer"),
            ("γλυκό,το", "γλυκό", "sweet; dessert; cake; candy"),
            ("παγωτό,το", "παγωτό", "ice cream"),
            ("κέικ,το", "κέικ", "cake"),
            ("μπισκότο,το", "μπισκότο", "biscuit; cookie"),
        ],
        "Ρήματα": [
            ("τρώω", None, "to eat"),
            ("πίνω", None, "to drink"),
            ("μαγειρεύω", None, "to cook"),
            ("ψήνω", None, "to bake; to grill; to roast"),
            ("τηγανίζω", None, "to fry"),
            ("βράζω", None, "to boil"),
            ("κόβω", None, "to cut"),
            ("ανακατεύω", None, "to stir; to mix"),
            ("δοκιμάζω", None, "to taste; to try"),
            ("παραγγέλνω", None, "to order"),
            ("σερβίρω", None, "to serve"),
            ("χορταίνω", None, "to be full; to have had enough"),
            ("πεινώ", None, "to be hungry"),
            ("διψώ", None, "to be thirsty"),
        ],
        "Εκφράσεις": [
            ("Καλή όρεξη!", None, "enjoy your meal! bon appétit!"),
            ("Τρώτε!", None, "eat up!; help yourself!"),
            ("Είναι νόστιμο", None, "it's delicious"),
            ("Πολύ νόστιμο!", None, "very tasty!"),
            ("Τι θα φάμε;", None, "what shall we eat?"),
            ("Πεινάω", None, "I'm hungry"),
            ("Διψάω", None, "I'm thirsty"),
            ("Χόρτασα", None, "I'm full; I've had enough"),
            ("Άλλο λίγο;", None, "a little more?"),
            ("Δεν τρώω...", None, "I don't eat..."),
        ],
        "Επίθετα": [
            ("νόστιμος/η/ο", None, "tasty; delicious"),
            ("άνοστος/η/ο", None, "tasteless; bland"),
            ("φρέσκος/η/ο", None, "fresh"),
            ("ζεστός/ή/ό", None, "warm; hot"),
            ("κρύος/α/ο", None, "cold"),
            ("γλυκός/ιά/ό", None, "sweet"),
            ("αλμυρός/ή/ό", None, "salty; savoury"),
            ("πικρός/ή/ό", None, "bitter"),
            ("ξινός/ή/ό", None, "sour"),
            ("매운/매운/매운", None, "spicy; hot"),  # placeholder - will fix
        ],
    }),

    (25, "Στην Πόλη — Out & About", {
        "Ουσιαστικά": [
            ("πόλη,η", "πόλη", "city; town"),
            ("χωριό,το", "χωριό", "village"),
            ("δρόμος,ο", "δρόμος", "street; road; way"),
            ("λεωφόρος,η", "λεωφόρος", "avenue; boulevard"),
            ("πλατεία,η", "πλατεία", "square; plaza"),
            ("γειτονιά,η", "γειτονιά", "neighbourhood"),
            ("κατάστημα,το", "κατάστημα", "shop; store"),
            ("σούπερμαρκετ,το", "σούπερμαρκετ", "supermarket"),
            ("φαρμακείο,το", "φαρμακείο", "pharmacy"),
            ("νοσοκομείο,το", "νοσοκομείο", "hospital"),
            ("σχολείο,το", "σχολείο", "school"),
            ("πανεπιστήμιο,το", "πανεπιστήμιο", "university"),
            ("τράπεζα,η", "τράπεζα", "bank; bench"),
            ("ταχυδρομείο,το", "ταχυδρομείο", "post office"),
            ("αστυνομία,η", "αστυνομία", "police"),
            ("πυροσβεστική,η", "πυροσβεστική", "fire brigade"),
            ("εκκλησία,η", "εκκλησία", "church"),
            ("μουσείο,το", "μουσείο", "museum"),
            ("πάρκο,το", "πάρκο", "park"),
            ("παραλία,η", "παραλία", "beach"),
            ("λιμάνι,το", "λιμάνι", "port; harbour"),
            ("αεροδρόμιο,το", "αεροδρόμιο", "airport"),
            ("σταθμός,ο", "σταθμός", "station"),
            ("στάση,η", "στάση", "stop (bus/tram)"),
            ("ταξί,το", "ταξί", "taxi"),
            ("λεωφορείο,το", "λεωφορείο", "bus"),
            ("μετρό,το", "μετρό", "metro; underground"),
            ("τρένο,το", "τρένο", "train"),
            ("αυτοκίνητο,το", "αυτοκίνητο", "car"),
            ("ποδήλατο,το", "ποδήλατο", "bicycle"),
        ],
        "Ρήματα": [
            ("πηγαίνω", None, "to go"),
            ("έρχομαι", None, "to come"),
            ("φεύγω", None, "to leave; to go away"),
            ("φτάνω", None, "to arrive; to reach"),
            ("στρίβω", None, "to turn"),
            ("συνεχίζω", None, "to continue; to keep going"),
            ("περνώ", None, "to pass; to cross; to spend (time)"),
            ("βρίσκω", None, "to find"),
            ("ψάχνω", None, "to look for; to search"),
            ("ρωτώ", None, "to ask"),
            ("χάνομαι", None, "to get lost"),
            ("σταματώ", None, "to stop"),
            ("παρκάρω", None, "to park"),
        ],
        "Εκφράσεις": [
            ("Πού είναι..;", None, "where is...?"),
            ("Πώς πάω στο/στη...;", None, "how do I get to...?"),
            ("Ευθεία", None, "straight ahead"),
            ("Αριστερά", None, "left; to the left"),
            ("Δεξιά", None, "right; to the right"),
            ("Κοντά", None, "near; close by"),
            ("Μακριά", None, "far; far away"),
            ("Στη γωνία", None, "at the corner"),
            ("Απέναντι", None, "opposite; across"),
            ("Δίπλα", None, "next to; beside"),
            ("Κάτω από", None, "under; below"),
            ("Πάνω από", None, "above; over"),
        ],
        "Επίθετα": [
            ("κοντινός/ή/ό", None, "near; nearby"),
            ("μακρινός/ή/ό", None, "far; distant"),
            ("γνωστός/ή/ό", None, "known; familiar"),
            ("άγνωστος/η/ο", None, "unknown; stranger"),
        ],
    }),

    (26, "Χρόνος & Ρουτίνα — Time & Daily Routine", {
        "Ουσιαστικά": [
            ("ώρα,η", "ώρα", "hour; time; o'clock"),
            ("λεπτό,το", "λεπτό", "minute"),
            ("δευτερόλεπτο,το", "δευτερόλεπτο", "second"),
            ("μέρα/μέρες,η", "μέρα", "day"),
            ("εβδομάδα,η", "εβδομάδα", "week"),
            ("μήνας,ο", "μήνας", "month"),
            ("χρόνος,ο", "χρόνος", "year; time"),
            ("χρονιά,η", "χρονιά", "year"),
            ("σήμερα", None, "today"),
            ("αύριο", None, "tomorrow"),
            ("χθες", None, "yesterday"),
            ("τώρα", None, "now"),
            ("αμέσως", None, "immediately; right away"),
            ("πρόσφατα", None, "recently"),
            ("σύντομα", None, "soon"),
            ("ποτέ", None, "never"),
            ("πάντα", None, "always"),
            ("συχνά", None, "often; frequently"),
            ("μερικές φορές", None, "sometimes"),
            ("σπάνια", None, "rarely; seldom"),
            ("Δευτέρα,η", "Δευτέρα", "Monday"),
            ("Τρίτη,η", "Τρίτη", "Tuesday"),
            ("Τετάρτη,η", "Τετάρτη", "Wednesday"),
            ("Πέμπτη,η", "Πέμπτη", "Thursday"),
            ("Παρασκευή,η", "Παρασκευή", "Friday"),
            ("Σάββατο,το", "Σάββατο", "Saturday"),
            ("Κυριακή,η", "Κυριακή", "Sunday"),
            ("Ιανουάριος,ο", "Ιανουάριος", "January"),
            ("Φεβρουάριος,ο", "Φεβρουάριος", "February"),
            ("Μάρτιος,ο", "Μάρτιος", "March"),
            ("Απρίλιος,ο", "Απρίλιος", "April"),
            ("Μάιος,ο", "Μάιος", "May"),
            ("Ιούνιος,ο", "Ιούνιος", "June"),
            ("Ιούλιος,ο", "Ιούλιος", "July"),
            ("Αύγουστος,ο", "Αύγουστος", "August"),
            ("Σεπτέμβριος,ο", "Σεπτέμβριος", "September"),
            ("Οκτώβριος,ο", "Οκτώβριος", "October"),
            ("Νοέμβριος,ο", "Νοέμβριος", "November"),
            ("Δεκέμβριος,ο", "Δεκέμβριος", "December"),
        ],
        "Ρήματα": [
            ("ξυπνώ", None, "to wake up"),
            ("σηκώνομαι", None, "to get up; to rise"),
            ("ετοιμάζομαι", None, "to get ready"),
            ("πηγαίνω", None, "to go"),
            ("επιστρέφω", None, "to return; to come back"),
            ("κοιμάμαι", None, "to sleep"),
            ("αργώ", None, "to be late; to take a long time"),
            ("βιάζομαι", None, "to be in a hurry"),
            ("προλαβαίνω", None, "to make it in time; to catch"),
            ("περιμένω", None, "to wait"),
            ("χάνω", None, "to miss; to lose"),
            ("προγραμματίζω", None, "to plan; to schedule"),
        ],
        "Εκφράσεις": [
            ("Τι ώρα είναι;", None, "what time is it?"),
            ("Είναι τρεις η ώρα", None, "it is three o'clock"),
            ("Στις οκτώ το πρωί", None, "at eight in the morning"),
            ("Το μεσημέρι", None, "at noon; in the middle of the day"),
            ("Το απόγευμα", None, "in the afternoon"),
            ("Το βράδυ", None, "in the evening"),
            ("Αυτή την εβδομάδα", None, "this week"),
            ("Την επόμενη εβδομάδα", None, "next week"),
            ("Πέρσι", None, "last year"),
            ("Φέτος", None, "this year"),
            ("Του χρόνου", None, "next year"),
        ],
    }),

    (27, "Ψώνια & Χρήματα — Shopping & Money", {
        "Ουσιαστικά": [
            ("χρήμα,το", "χρήμα", "money"),
            ("λεφτά,τα", "λεφτά", "money (colloquial)"),
            ("τιμή,η", "τιμή", "price; honour"),
            ("ευρώ,το", "ευρώ", "euro"),
            ("κέρμα,το", "κέρμα", "coin"),
            ("χαρτονόμισμα,το", "χαρτονόμισμα", "banknote"),
            ("λογαριασμός,ο", "λογαριασμός", "bill; account; invoice"),
            ("απόδειξη,η", "απόδειξη", "receipt"),
            ("έκπτωση,η", "έκπτωση", "discount; sale"),
            ("προσφορά,η", "προσφορά", "offer; deal; sale"),
            ("αγορά,η", "αγορά", "market; shopping; purchase"),
            ("σούπερ μάρκετ,το", "σούπερ μάρκετ", "supermarket"),
            ("φούρνος,ο", "φούρνος", "bakery; oven"),
            ("χασάπης,ο", "χασάπης", "butcher"),
            ("ψαράς,ο", "ψαράς", "fishmonger; fisherman"),
            ("λαϊκή αγορά,η", "λαϊκή αγορά", "farmers' market; open market"),
            ("ταμείο,το", "ταμείο", "cashier; checkout; till"),
            ("καλάθι,το", "καλάθι", "basket"),
            ("τσάντα,η", "τσάντα", "bag; handbag"),
            ("κάρτα,η", "κάρτα", "card (payment)"),
            ("ATM,το", "ATM", "ATM; cash machine"),
            ("ψώνια,τα", "ψώνια", "shopping; groceries"),
        ],
        "Ρήματα": [
            ("ψωνίζω", None, "to shop; to go shopping"),
            ("αγοράζω", None, "to buy; to purchase"),
            ("πουλώ", None, "to sell"),
            ("πληρώνω", None, "to pay"),
            ("κοστίζω", None, "to cost"),
            ("χρωστώ", None, "to owe"),
            ("ανταλλάσσω", None, "to exchange"),
            ("επιστρέφω", None, "to return (an item)"),
            ("παζαρεύω", None, "to bargain; to haggle"),
            ("εξοδεύω", None, "to spend (money)"),
            ("οικονομώ", None, "to save (money); to be economical"),
        ],
        "Εκφράσεις": [
            ("Πόσο κάνει;", None, "how much does it cost?"),
            ("Πόσο κοστίζει;", None, "how much does it cost?"),
            ("Είναι ακριβό", None, "it's expensive"),
            ("Είναι φτηνό", None, "it's cheap"),
            ("Μπορώ να δω..;", None, "can I see...?"),
            ("Θα το πάρω", None, "I'll take it"),
            ("Δεν το θέλω", None, "I don't want it"),
            ("Έχετε..;", None, "do you have...?"),
            ("Με κάρτα ή μετρητά;", None, "card or cash?"),
            ("Κρατήστε τα ρέστα", None, "keep the change"),
        ],
        "Επίθετα": [
            ("ακριβός/ή/ό", None, "expensive; dear; exact"),
            ("φτηνός/ή/ό", None, "cheap; inexpensive"),
            ("δωρεάν", None, "free (of charge)"),
            ("καινούριος/α/ο", None, "new; brand new"),
            ("μεταχειρισμένος/η/ο", None, "used; second-hand"),
            ("φρέσκος/η/ο", None, "fresh"),
            ("εκπτωτικός/ή/ό", None, "on sale; discounted"),
        ],
    }),

    (28, "Το Σώμα & Η Υγεία — Body & Health", {
        "Ουσιαστικά": [
            ("σώμα,το", "σώμα", "body"),
            ("κεφάλι,το", "κεφάλι", "head"),
            ("πρόσωπο,το", "πρόσωπο", "face"),
            ("μάτι,το", "μάτι", "eye"),
            ("αυτί,το", "αυτί", "ear"),
            ("μύτη,η", "μύτη", "nose"),
            ("στόμα,το", "στόμα", "mouth"),
            ("δόντι,το", "δόντι", "tooth"),
            ("γλώσσα,η", "γλώσσα", "tongue; language"),
            ("λαιμός,ο", "λαιμός", "throat; neck"),
            ("ώμος,ο", "ώμος", "shoulder"),
            ("χέρι,το", "χέρι", "hand; arm"),
            ("δάχτυλο,το", "δάχτυλο", "finger; toe"),
            ("πλάτη,η", "πλάτη", "back"),
            ("κοιλιά,η", "κοιλιά", "stomach; belly"),
            ("πόδι,το", "πόδι", "foot; leg"),
            ("γόνατο,το", "γόνατο", "knee"),
            ("καρδιά,η", "καρδιά", "heart"),
            ("πνεύμονας,ο", "πνεύμονας", "lung"),
            ("νεφρό,το", "νεφρό", "kidney"),
            ("γιατρός,ο/η", "γιατρός", "doctor"),
            ("νοσοκόμα,η", "νοσοκόμα", "nurse (female)"),
            ("νοσοκομείο,το", "νοσοκομείο", "hospital"),
            ("φαρμακείο,το", "φαρμακείο", "pharmacy"),
            ("φάρμακο,το", "φάρμακο", "medicine; drug"),
            ("χάπι,το", "χάπι", "pill; tablet"),
            ("πονοκέφαλος,ο", "πονοκέφαλος", "headache"),
            ("πυρετός,ο", "πυρετός", "fever; temperature"),
            ("κρυολόγημα,το", "κρυολόγημα", "cold (illness)"),
            ("γρίπη,η", "γρίπη", "flu; influenza"),
            ("πόνος,ο", "πόνος", "pain; ache"),
            ("τραύμα,το", "τραύμα", "wound; injury; trauma"),
            ("αλλεργία,η", "αλλεργία", "allergy"),
        ],
        "Ρήματα": [
            ("πονώ", None, "to hurt; to ache"),
            ("αρρωσταίνω", None, "to get sick"),
            ("αρρωστώ", None, "to be sick"),
            ("θεραπεύω", None, "to treat; to heal; to cure"),
            ("εξετάζω", None, "to examine; to check"),
            ("παίρνω φάρμακο", None, "to take medicine"),
            ("αναρρώνω", None, "to recover; to convalesce"),
            ("τραυματίζω", None, "to injure; to wound"),
            ("κόβω", None, "to cut"),
            ("χτυπώ", None, "to hit; to knock"),
            ("αναπνέω", None, "to breathe"),
            ("βήχω", None, "to cough"),
            ("φτερνίζομαι", None, "to sneeze"),
            ("ιδρώνω", None, "to sweat"),
        ],
        "Εκφράσεις": [
            ("Με πονάει...", None, "my ... hurts"),
            ("Δεν αισθάνομαι καλά", None, "I don't feel well"),
            ("Είμαι άρρωστος/η", None, "I am sick"),
            ("Έχω πυρετό", None, "I have a fever"),
            ("Έχω πονοκέφαλο", None, "I have a headache"),
            ("Πάμε στον γιατρό", None, "let's go to the doctor"),
            ("Χρειάζομαι φάρμακο", None, "I need medicine"),
            ("Περνάει σύντομα", None, "it'll pass soon"),
        ],
    }),

    (29, "Ο Καιρός & Η Φύση — Weather & Nature", {
        "Ουσιαστικά": [
            ("καιρός,ο", "καιρός", "weather; time"),
            ("θερμοκρασία,η", "θερμοκρασία", "temperature"),
            ("ήλιος,ο", "ήλιος", "sun"),
            ("βροχή,η", "βροχή", "rain"),
            ("χιόνι,το", "χιόνι", "snow"),
            ("αέρας,ο", "αέρας", "wind; air"),
            ("καταιγίδα,η", "καταιγίδα", "storm; thunderstorm"),
            ("αστραπή,η", "αστραπή", "lightning"),
            ("βροντή,η", "βροντή", "thunder"),
            ("ομίχλη,η", "ομίχλη", "fog; mist"),
            ("σύννεφο,το", "σύννεφο", "cloud"),
            ("ουρανός,ο", "ουρανός", "sky; heaven"),
            ("ουράνιο τόξο,το", "ουράνιο τόξο", "rainbow"),
            ("εποχή,η", "εποχή", "season; era"),
            ("άνοιξη,η", "άνοιξη", "spring"),
            ("καλοκαίρι,το", "καλοκαίρι", "summer"),
            ("φθινόπωρο,το", "φθινόπωρο", "autumn; fall"),
            ("χειμώνας,ο", "χειμώνας", "winter"),
            ("θάλασσα,η", "θάλασσα", "sea"),
            ("βουνό,το", "βουνό", "mountain"),
            ("ποτάμι,το", "ποτάμι", "river"),
            ("λίμνη,η", "λίμνη", "lake"),
            ("δάσος,το", "δάσος", "forest; wood"),
            ("λουλούδι,το", "λουλούδι", "flower"),
            ("δέντρο,το", "δέντρο", "tree"),
            ("χορτάρι,το", "χορτάρι", "grass; herb"),
            ("τοπίο,το", "τοπίο", "landscape; scenery"),
        ],
        "Ρήματα": [
            ("βρέχει", None, "it rains; it is raining"),
            ("χιονίζει", None, "it snows; it is snowing"),
            ("φυσάει", None, "it blows; it is windy"),
            ("λιάζομαι", None, "to sunbathe"),
            ("κρυώνω", None, "to be cold; to get cold"),
            ("ζεσταίνομαι", None, "to get warm; to warm up"),
            ("βρέχομαι", None, "to get wet"),
            ("στεγνώνω", None, "to dry"),
        ],
        "Εκφράσεις": [
            ("Τι καιρό κάνει;", None, "what's the weather like?"),
            ("Κάνει ζέστη", None, "it's hot"),
            ("Κάνει κρύο", None, "it's cold"),
            ("Έχει ήλιο", None, "it's sunny"),
            ("Έχει αέρα", None, "it's windy"),
            ("Συννεφιάζει", None, "it's clouding over"),
            ("Θα βρέξει", None, "it's going to rain"),
            ("Ωραίος καιρός!", None, "nice weather!"),
        ],
        "Επίθετα": [
            ("ζεστός/ή/ό", None, "warm; hot"),
            ("κρύος/α/ο", None, "cold"),
            ("συννεφιασμένος/η/ο", None, "cloudy; overcast"),
            ("αίθριος/α/ο", None, "clear; sunny (weather)"),
            ("υγρός/ή/ό", None, "wet; humid; damp"),
            ("ξηρός/ή/ό", None, "dry"),
            ("ηλιόλουστος/η/ο", None, "sunny"),
            ("καταιγιδοφόρος/α/ο", None, "stormy"),
        ],
    }),

    (30, "Παιδιά & Σχολείο — Children & School", {
        "Ουσιαστικά": [
            ("σχολείο,το", "σχολείο", "school"),
            ("τάξη,η", "τάξη", "class; classroom; grade"),
            ("μάθημα,το", "μάθημα", "lesson; subject; homework"),
            ("βιβλίο,το", "βιβλίο", "book"),
            ("τετράδιο,το", "τετράδιο", "notebook; exercise book"),
            ("μολύβι,το", "μολύβι", "pencil"),
            ("στυλό,το", "στυλό", "pen"),
            ("σβηστήρα,η", "σβηστήρα", "eraser; rubber"),
            ("χάρακας,ο", "χάρακας", "ruler"),
            ("σακίδιο,το", "σακίδιο", "backpack; school bag"),
            ("δάσκαλος,ο", "δάσκαλος", "teacher (primary, male)"),
            ("δασκάλα,η", "δασκάλα", "teacher (primary, female)"),
            ("καθηγητής,ο", "καθηγητής", "professor; teacher (secondary, male)"),
            ("καθηγήτρια,η", "καθηγήτρια", "professor; teacher (secondary, female)"),
            ("μαθητής,ο", "μαθητής", "pupil; student (male)"),
            ("μαθήτρια,η", "μαθήτρια", "pupil; student (female)"),
            ("εξέταση,η", "εξέταση", "exam; test"),
            ("βαθμός,ο", "βαθμός", "grade; mark; degree"),
            ("παιχνίδι,το", "παιχνίδι", "game; toy"),
            ("παιδική χαρά,η", "παιδική χαρά", "playground"),
            ("διάλειμμα,το", "διάλειμμα", "break; recess"),
            ("ωράριο,το", "ωράριο", "schedule; timetable"),
            ("γυμναστήριο,το", "γυμναστήριο", "gym; gymnasium"),
            ("εγγραφή,η", "εγγραφή", "enrollment; registration"),
            ("βαθμολογία,η", "βαθμολογία", "grade sheet; marks"),
        ],
        "Ρήματα": [
            ("μαθαίνω", None, "to learn; to teach"),
            ("διδάσκω", None, "to teach"),
            ("σπουδάζω", None, "to study"),
            ("διαβάζω", None, "to read; to study"),
            ("γράφω", None, "to write"),
            ("ζωγραφίζω", None, "to draw; to paint"),
            ("μετρώ", None, "to count"),
            ("λύνω", None, "to solve"),
            ("κάνω εξέταση", None, "to take an exam"),
            ("περνώ", None, "to pass (exam)"),
            ("κόβομαι", None, "to fail (exam, colloquial)"),
            ("επαναλαμβάνω", None, "to repeat; to revise"),
            ("κάνω κάτι", None, "to do something"),
        ],
        "Εκφράσεις": [
            ("Τι έμαθες σήμερα;", None, "what did you learn today?"),
            ("Έχεις διαβάσει;", None, "have you studied?"),
            ("Κάνε τα μαθήματά σου", None, "do your homework"),
            ("Πάμε σχολείο!", None, "let's go to school!"),
            ("Πήρα καλό βαθμό", None, "I got a good grade"),
            ("Είμαι πρώτος/η στην τάξη", None, "I'm first in class"),
            ("Μπράβο!", None, "well done! bravo!"),
        ],
        "Επίθετα": [
            ("έξυπνος/η/ο", None, "clever; smart; intelligent"),
            ("επιμελής/ής/ές", None, "diligent; studious"),
            ("τεμπέλης/α/ικο", None, "lazy"),
            ("περίεργος/η/ο", None, "curious; strange"),
            ("δυνατός/ή/ό", None, "strong; loud; good at something"),
            ("αδύναμος/η/ο", None, "weak"),
            ("ικανός/ή/ό", None, "capable; able"),
        ],
    }),

    (31, "Ρήματα Κίνησης & Δράσης — Movement & Action Verbs", {
        "Ρήματα": [
            ("πηγαίνω", None, "to go"),
            ("έρχομαι", None, "to come"),
            ("φεύγω", None, "to leave; to go away"),
            ("φτάνω", None, "to arrive; to reach; to be enough"),
            ("επιστρέφω", None, "to return"),
            ("περπατώ", None, "to walk"),
            ("τρέχω", None, "to run"),
            ("πηδώ", None, "to jump; to skip"),
            ("στέκομαι", None, "to stand"),
            ("κάθομαι", None, "to sit; to stay"),
            ("ξαπλώνω", None, "to lie down"),
            ("σηκώνομαι", None, "to get up; to rise; to lift"),
            ("ανεβαίνω", None, "to go up; to climb; to board"),
            ("κατεβαίνω", None, "to go down; to descend; to get off"),
            ("μπαίνω", None, "to enter; to go in"),
            ("βγαίνω", None, "to exit; to go out"),
            ("ανοίγω", None, "to open"),
            ("κλείνω", None, "to close; to book"),
            ("παίρνω", None, "to take; to get; to pick up"),
            ("δίνω", None, "to give"),
            ("βάζω", None, "to put; to place"),
            ("βγάζω", None, "to take out; to remove"),
            ("φέρνω", None, "to bring"),
            ("πηγαίνω φέρε", None, "to go and get; fetch"),
            ("σπρώχνω", None, "to push"),
            ("τραβώ", None, "to pull; to draw"),
            ("κρατώ", None, "to hold; to keep"),
            ("αφήνω", None, "to leave; to let; to allow"),
            ("πετώ", None, "to fly; to throw"),
            ("πιάνω", None, "to catch; to grab"),
            ("χτυπώ", None, "to knock; to hit; to ring"),
            ("σπάω", None, "to break"),
            ("χύνω", None, "to spill; to pour"),
            ("σκάω", None, "to burst; to explode"),
            ("κόβω", None, "to cut"),
            ("δένω", None, "to tie; to bind"),
            ("λύνω", None, "to untie; to solve"),
            ("χάνω", None, "to lose; to miss"),
            ("βρίσκω", None, "to find"),
            ("ψάχνω", None, "to search; to look for"),
            ("παρατώ", None, "to abandon; to give up"),
            ("αρχίζω", None, "to begin; to start"),
            ("τελειώνω", None, "to finish; to end"),
            ("συνεχίζω", None, "to continue"),
            ("σταματώ", None, "to stop"),
            ("επαναλαμβάνω", None, "to repeat; to do again"),
            ("αλλάζω", None, "to change"),
            ("φτιάχνω", None, "to fix; to make; to prepare"),
            ("σπάω", None, "to break"),
            ("χρησιμοποιώ", None, "to use"),
        ],
    }),

    (32, "Ρήματα Σκέψης & Επικοινωνίας — Thinking & Communication Verbs", {
        "Ρήματα": [
            ("λέω", None, "to say; to tell"),
            ("μιλώ", None, "to talk; to speak"),
            ("ρωτώ", None, "to ask"),
            ("απαντώ", None, "to answer; to reply"),
            ("εξηγώ", None, "to explain"),
            ("περιγράφω", None, "to describe"),
            ("αφηγούμαι", None, "to narrate; to tell a story"),
            ("παραπονιέμαι", None, "to complain"),
            ("υπόσχομαι", None, "to promise"),
            ("ορκίζομαι", None, "to swear; to take an oath"),
            ("συμφωνώ", None, "to agree"),
            ("διαφωνώ", None, "to disagree"),
            ("συζητώ", None, "to discuss; to argue"),
            ("μαλώνω", None, "to argue; to quarrel"),
            ("φιλονικώ", None, "to quarrel; to bicker"),
            ("σκέφτομαι", None, "to think"),
            ("ξέρω", None, "to know"),
            ("καταλαβαίνω", None, "to understand"),
            ("θυμάμαι", None, "to remember"),
            ("ξεχνώ", None, "to forget"),
            ("μαθαίνω", None, "to learn"),
            ("πιστεύω", None, "to believe; to think"),
            ("αμφιβάλλω", None, "to doubt"),
            ("φαντάζομαι", None, "to imagine"),
            ("ονειρεύομαι", None, "to dream"),
            ("ελπίζω", None, "to hope"),
            ("επιμένω", None, "to insist"),
            ("παραδέχομαι", None, "to admit; to acknowledge"),
            ("αρνούμαι", None, "to refuse; to deny"),
            ("αποφασίζω", None, "to decide"),
            ("εννοώ", None, "to mean; to intend"),
            ("θέλω", None, "to want"),
            ("προτιμώ", None, "to prefer"),
            ("διαλέγω", None, "to choose"),
            ("κρίνω", None, "to judge"),
            ("αξιολογώ", None, "to evaluate"),
            ("προτείνω", None, "to suggest; to propose"),
            ("συστήνω", None, "to recommend; to introduce"),
            ("παρακαλώ", None, "to please; to beg"),
            ("ευχαριστώ", None, "to thank"),
            ("συγχωρώ", None, "to forgive"),
            ("κατηγορώ", None, "to accuse"),
            ("υποστηρίζω", None, "to support; to argue for"),
            ("αποδεικνύω", None, "to prove"),
            ("αναρωτιέμαι", None, "to wonder; to ask oneself"),
        ],
    }),

    (33, "Επίθετα Χαρακτήρα — Personality & Character", {
        "Επίθετα": [
            ("καλός/ή/ό", None, "good; kind"),
            ("κακός/ή/ό", None, "bad; evil; mean"),
            ("γλυκός/ιά/ό", None, "sweet; kind; gentle"),
            ("αγαθός/ή/ό", None, "good-natured; virtuous"),
            ("ευγενικός/ή/ό", None, "polite; kind; noble"),
            ("αγενής/ής/ές", None, "rude; impolite"),
            ("έξυπνος/η/ο", None, "clever; smart"),
            ("ανόητος/η/ο", None, "foolish; stupid"),
            ("σοφός/ή/ό", None, "wise"),
            ("αφελής/ής/ές", None, "naive; simple"),
            ("γενναίος/α/ο", None, "brave; courageous"),
            ("δειλός/ή/ό", None, "cowardly"),
            ("τολμηρός/ή/ό", None, "daring; bold"),
            ("φιλικός/ή/ό", None, "friendly"),
            ("κοινωνικός/ή/ό", None, "sociable; social"),
            ("αντικοινωνικός/ή/ό", None, "antisocial; unsociable"),
            ("ντροπαλός/ή/ό", None, "shy; bashful"),
            ("τεμπέλης/α/ικο", None, "lazy"),
            ("επιμελής/ής/ές", None, "diligent; hardworking"),
            ("υπομονετικός/ή/ό", None, "patient"),
            ("ανυπόμονος/η/ο", None, "impatient"),
            ("γελαστός/ή/ό", None, "cheerful; always smiling"),
            ("σοβαρός/ή/ό", None, "serious"),
            ("αστείος/α/ο", None, "funny; joking"),
            ("ειλικρινής/ής/ές", None, "sincere; honest"),
            ("ψεύτης/α/ικο", None, "liar; dishonest"),
            ("εγωιστής/ή/ές", None, "selfish; egotistical"),
            ("γενναιόδωρος/η/ο", None, "generous"),
            ("τσιγκούνης/α/ικο", None, "stingy; miserly"),
            ("περίεργος/η/ο", None, "curious; nosy; strange"),
            ("δημιουργικός/ή/ό", None, "creative"),
            ("πρακτικός/ή/ό", None, "practical"),
            ("ευαίσθητος/η/ο", None, "sensitive"),
            ("σκληρός/ή/ό", None, "hard; harsh; tough"),
            ("τρυφερός/ή/ό", None, "tender; gentle; affectionate"),
            ("ζηλιάρης/α/ικο", None, "jealous"),
            ("φθονερός/ή/ό", None, "envious"),
            ("υπερήφανος/η/ο", None, "proud; arrogant"),
            ("ταπεινός/ή/ό", None, "humble"),
            ("αξιόπιστος/η/ο", None, "reliable; trustworthy"),
            ("αναξιόπιστος/η/ο", None, "unreliable"),
            ("σπάταλος/η/ο", None, "wasteful; extravagant"),
            ("λογικός/ή/ό", None, "logical; reasonable"),
            ("παράλογος/η/ο", None, "irrational; absurd"),
            ("αδέξιος/α/ο", None, "clumsy; awkward"),
            ("επιδέξιος/α/ο", None, "skilful; dexterous"),
            ("φιλόδοξος/η/ο", None, "ambitious"),
            ("τυχοδιώκτης/ρια/ικο", None, "adventurous; risk-taking"),
            ("ήρεμος/η/ο", None, "calm; tranquil"),
            ("νευρικός/ή/ό", None, "nervous; irritable"),
        ],
    }),

    (34, "Επίθετα & Αντίθετα — Common Adjectives & Opposites", {
        "Επίθετα": [
            ("μεγάλος/η/ο", None, "big; large; great; old (person)"),
            ("μικρός/ή/ό", None, "small; little; young"),
            ("ψηλός/ή/ό", None, "tall; high"),
            ("κοντός/ή/ό", None, "short; low"),
            ("παχύς/ιά/ύ", None, "fat; thick"),
            ("αδύνατος/η/ο", None, "thin; weak"),
            ("δυνατός/ή/ό", None, "strong; powerful; loud"),
            ("καινούριος/α/ο", None, "new"),
            ("παλιός/ά/ό", None, "old; former"),
            ("όμορφος/η/ο", None, "beautiful; handsome"),
            ("άσχημος/η/ο", None, "ugly"),
            ("γρήγορος/η/ο", None, "fast; quick"),
            ("αργός/ή/ό", None, "slow"),
            ("εύκολος/η/ο", None, "easy"),
            ("δύσκολος/η/ο", None, "difficult; hard"),
            ("ακριβής/ής/ές", None, "accurate; exact; expensive"),
            ("λάθος", None, "wrong; mistaken (invariable)"),
            ("σωστός/ή/ό", None, "correct; right"),
            ("ανοιχτός/ή/ό", None, "open"),
            ("κλειστός/ή/ό", None, "closed"),
            ("πλήρης/ης/ες", None, "full; complete"),
            ("άδειος/α/ο", None, "empty"),
            ("βαρύς/ιά/ύ", None, "heavy"),
            ("ελαφρύς/ιά/ύ", None, "light (in weight)"),
            ("βαθύς/ιά/ύ", None, "deep"),
            ("ρηχός/ή/ό", None, "shallow"),
            ("στενός/ή/ό", None, "narrow; tight"),
            ("φαρδύς/ιά/ύ", None, "wide; broad"),
            ("καθαρός/ή/ό", None, "clean; clear"),
            ("βρώμικος/η/ο", None, "dirty"),
            ("ωραίος/α/ο", None, "nice; beautiful"),
            ("άσχημος/η/ο", None, "ugly"),
            ("ακριβός/ή/ό", None, "expensive"),
            ("φτηνός/ή/ό", None, "cheap"),
            ("σκληρός/ή/ό", None, "hard; tough"),
            ("μαλακός/ή/ό", None, "soft"),
            ("κρύος/α/ο", None, "cold"),
            ("ζεστός/ή/ό", None, "warm; hot"),
            ("φωτεινός/ή/ό", None, "bright; light"),
            ("σκοτεινός/ή/ό", None, "dark; gloomy"),
            ("ήσυχος/η/ο", None, "quiet; peaceful"),
            ("θορυβώδης/ης/ες", None, "noisy"),
            ("νόστιμος/η/ο", None, "tasty; delicious"),
            ("άνοστος/η/ο", None, "tasteless"),
            ("χρήσιμος/η/ο", None, "useful"),
            ("άχρηστος/η/ο", None, "useless"),
            ("ελεύθερος/η/ο", None, "free; available"),
            ("απασχολημένος/η/ο", None, "busy; occupied"),
            ("ευτυχισμένος/η/ο", None, "happy"),
            ("δυστυχισμένος/η/ο", None, "unhappy"),
        ],
    }),

    (35, "Προθέσεις & Σύνδεσμοι — Prepositions & Conjunctions", {
        "Ουσιαστικά": [
            ("πρόθεση,η", "πρόθεση", "preposition; intention"),
            ("σύνδεσμος,ο", "σύνδεσμος", "conjunction; link; connector"),
            ("επίρρημα,το", "επίρρημα", "adverb"),
        ],
        "Εκφράσεις": [
            # Prepositions of place
            ("σε", None, "in; at; to; on"),
            ("από", None, "from; of; by; since"),
            ("για", None, "for; about; to"),
            ("με", None, "with"),
            ("χωρίς", None, "without"),
            ("μέχρι", None, "until; up to; as far as"),
            ("ως", None, "until; as; to (formal)"),
            ("κατά", None, "against; towards; per; approximately"),
            ("μετά", None, "after; then"),
            ("πριν", None, "before"),
            ("πάνω", None, "up; above; on top"),
            ("κάτω", None, "down; below; under"),
            ("μέσα", None, "inside; within; in"),
            ("έξω", None, "outside; out"),
            ("μπροστά", None, "in front; forward"),
            ("πίσω", None, "behind; back"),
            ("δίπλα", None, "next to; beside"),
            ("κοντά", None, "near; close"),
            ("μακριά", None, "far; away"),
            ("ανάμεσα", None, "between; among"),
            ("γύρω", None, "around"),
            ("απέναντι", None, "opposite; across"),
            ("εκτός", None, "except; outside of; apart from"),
            ("εντός", None, "within; inside of"),
            # Conjunctions
            ("και", None, "and"),
            ("ή", None, "or"),
            ("αλλά", None, "but"),
            ("όμως", None, "however; but; yet"),
            ("γιατί", None, "because; why"),
            ("επειδή", None, "because; since"),
            ("άρα", None, "so; therefore; then"),
            ("λοιπόν", None, "so; well then; anyway"),
            ("ότι", None, "that (conjunction)"),
            ("αν", None, "if"),
            ("εάν", None, "if (formal)"),
            ("όταν", None, "when"),
            ("ενώ", None, "while; whereas"),
            ("μολονότι", None, "although; even though"),
            ("παρόλο που", None, "although; despite the fact that"),
            ("ώσπου", None, "until"),
            ("μόλις", None, "as soon as; just"),
            ("καθώς", None, "as; since"),
            ("ώστε", None, "so that; in order to"),
            ("για να", None, "in order to; so that"),
            ("αφού", None, "since; after"),
            ("εκτός αν", None, "unless"),
            ("μάλιστα", None, "in fact; indeed; yes"),
            ("δηλαδή", None, "that is; namely; in other words"),
            ("επίσης", None, "also; as well; too"),
            ("ακόμα", None, "still; yet; even; also"),
            ("μόνο", None, "only; just"),
            ("τουλάχιστον", None, "at least"),
        ],
    }),

    (36, "Αριθμοί & Ποσότητες — Numbers & Quantities", {
        "Ουσιαστικά": [
            ("ένα/μια/ένα", None, "one"),
            ("δύο", None, "two"),
            ("τρία", None, "three"),
            ("τέσσερα", None, "four"),
            ("πέντε", None, "five"),
            ("έξι", None, "six"),
            ("επτά", None, "seven"),
            ("οκτώ", None, "eight"),
            ("εννέα", None, "nine"),
            ("δέκα", None, "ten"),
            ("έντεκα", None, "eleven"),
            ("δώδεκα", None, "twelve"),
            ("δεκατρία", None, "thirteen"),
            ("δεκατέσσερα", None, "fourteen"),
            ("δεκαπέντε", None, "fifteen"),
            ("είκοσι", None, "twenty"),
            ("τριάντα", None, "thirty"),
            ("σαράντα", None, "forty"),
            ("πενήντα", None, "fifty"),
            ("εξήντα", None, "sixty"),
            ("εβδομήντα", None, "seventy"),
            ("ογδόντα", None, "eighty"),
            ("ενενήντα", None, "ninety"),
            ("εκατό", None, "one hundred"),
            ("χίλια", None, "one thousand"),
            ("εκατομμύριο,το", "εκατομμύριο", "million"),
            ("πρώτος/η/ο", None, "first"),
            ("δεύτερος/η/ο", None, "second"),
            ("τρίτος/η/ο", None, "third"),
            ("τέταρτος/η/ο", None, "fourth"),
            ("πέμπτος/η/ο", None, "fifth"),
            ("τελευταίος/α/ο", None, "last"),
            ("μισός/ή/ό", None, "half"),
            ("τέταρτο,το", "τέταρτο", "quarter"),
            ("διπλός/ή/ό", None, "double"),
            ("τριπλός/ή/ό", None, "triple"),
        ],
        "Εκφράσεις": [
            ("λίγο", None, "a little; a bit; few"),
            ("λίγοι/ες/α", None, "few; not many"),
            ("πολύ", None, "very; much; a lot"),
            ("πολλοί/ές/ά", None, "many; a lot of"),
            ("αρκετός/ή/ό", None, "enough; quite a lot"),
            ("καθόλου", None, "not at all; none"),
            ("τίποτα", None, "nothing; anything"),
            ("κάτι", None, "something; a bit"),
            ("μερικοί/ές/ά", None, "some; a few"),
            ("κάθε", None, "every; each"),
            ("όλος/η/ο", None, "all; whole; entire"),
            ("περισσότεροι/ες/α", None, "more; most"),
            ("λιγότεροι/ες/α", None, "fewer; less"),
            ("τόσος/η/ο", None, "so much; so many; such"),
            ("όσος/η/ο", None, "as much as; as many as"),
            ("ακριβώς", None, "exactly; precisely"),
            ("περίπου", None, "approximately; about"),
            ("σχεδόν", None, "almost; nearly"),
        ],
    }),

    (37, "Ελληνική Κουζίνα — Greek Food & Cuisine", {
        "Ουσιαστικά": [
            ("μουσακάς,ο", "μουσακάς", "moussaka (baked dish with aubergine and minced meat)"),
            ("παστίτσιο,το", "παστίτσιο", "pastitsio (baked pasta with minced meat)"),
            ("σουβλάκι,το", "σουβλάκι", "souvlaki (grilled meat skewer)"),
            ("γύρος,ο", "γύρος", "gyros (rotisserie meat wrap)"),
            ("τζατζίκι,το", "τζατζίκι", "tzatziki (yoghurt, cucumber, garlic dip)"),
            ("χωριάτικη σαλάτα,η", "χωριάτικη σαλάτα", "Greek salad"),
            ("σπανακόπιτα,η", "σπανακόπιτα", "spinach pie"),
            ("τυρόπιτα,η", "τυρόπιτα", "cheese pie"),
            ("ταραμοσαλάτα,η", "ταραμοσαλάτα", "taramasalata (fish roe dip)"),
            ("κεφτέδες,οι", "κεφτέδες", "meatballs"),
            ("ντολμάδες,οι", "ντολμάδες", "dolmades (stuffed vine leaves)"),
            ("φακές,οι", "φακές", "lentils; lentil soup"),
            ("μπριάμ,το", "μπριάμ", "briam (baked mixed vegetables)"),
            ("κλέφτικο,το", "κλέφτικο", "kleftiko (slow-cooked lamb)"),
            ("στιφάδο,το", "στιφάδο", "stifado (stew with onions)"),
            ("σαγανάκι,το", "σαγανάκι", "saganaki (fried cheese)"),
            ("καλαμαράκια,τα", "καλαμαράκια", "fried squid; calamari"),
            ("χταπόδι,το", "χταπόδι", "octopus"),
            ("μπακαλιάρος,ο", "μπακαλιάρος", "salted cod"),
            ("ψητό,το", "ψητό", "roast; grilled food"),
            ("μεζές,ο", "μεζές", "meze (small dish)"),
            ("ορεκτικό,το", "ορεκτικό", "appetiser; starter"),
            ("ελαιόλαδο,το", "ελαιόλαδο", "olive oil"),
            ("ρίγανη,η", "ρίγανη", "oregano"),
            ("θυμάρι,το", "θυμάρι", "thyme"),
            ("δεντρολίβανο,το", "δεντρολίβανο", "rosemary"),
            ("λεμόνι,το", "λεμόνι", "lemon"),
            ("σκόρδο,το", "σκόρδο", "garlic"),
            ("κρεμμύδι,το", "κρεμμύδι", "onion"),
            ("μελιτζάνα,η", "μελιτζάνα", "aubergine; eggplant"),
            ("κολοκυθάκι,το", "κολοκυθάκι", "courgette; zucchini"),
            ("πιπεριά,η", "πιπεριά", "pepper (vegetable)"),
            ("φασόλια,τα", "φασόλια", "beans"),
            ("ρεβύθια,τα", "ρεβύθια", "chickpeas"),
            ("φρέσκος χυμός,ο", "φρέσκος χυμός", "fresh juice"),
            ("καφές ελληνικός,ο", "καφές ελληνικός", "Greek coffee"),
            ("φραπές,ο", "φραπές", "frappé (iced instant coffee)"),
            ("ούζο,το", "ούζο", "ouzo (anise spirit)"),
            ("τσίπουρο,το", "τσίπουρο", "tsipouro (grape spirit)"),
            ("μπακλαβάς,ο", "μπακλαβάς", "baklava (honey-nut pastry)"),
            ("λουκουμάς,ο", "λουκουμάς", "loukoumades (honey doughnuts)"),
            ("ρυζόγαλο,το", "ρυζόγαλο", "rice pudding"),
            ("γαλακτομπούρεκο,το", "γαλακτομπούρεκο", "galaktoboureko (custard pastry)"),
        ],
        "Εκφράσεις": [
            ("Να το 'χεις σαν ευλογία!", None, "may it be blessed! (said before eating)"),
            ("Καλή όρεξη!", None, "enjoy your meal!"),
            ("Στην υγειά μας!", None, "to our health! cheers!"),
            ("Γεια μας!", None, "cheers! (literally: to our health)"),
            ("Από χέρια σου!", None, "from your hands! (compliment to cook)"),
            ("Είναι σπιτικό", None, "it's home-made"),
            ("Έγλειψα τα δάκτυλά μου", None, "I licked my fingers (it was delicious)"),
            ("Τρώω σαν αγρίμι", None, "I'm eating like a wild animal (very hungry)"),
        ],
    }),

    (38, "Ελληνικές Εκφράσεις — Everyday Idioms & Expressions", {
        "Εκφράσεις": [
            ("Τι να κάνουμε;", None, "what can we do? (resignation)"),
            ("Δεν πειράζει", None, "it doesn't matter; never mind"),
            ("Έτσι είναι η ζωή", None, "that's life; c'est la vie"),
            ("Τι ζωή!", None, "what a life!"),
            ("Άντε!", None, "come on! go on! get out of here! (many uses)"),
            ("Άντε γεια", None, "goodbye (casual dismissal)"),
            ("Μπράβο!", None, "well done! bravo!"),
            ("Ωραία!", None, "great! lovely! nice!"),
            ("Τέλεια!", None, "perfect! excellent!"),
            ("Απίστευτο!", None, "unbelievable! incredible!"),
            ("Τι κρίμα!", None, "what a pity! what a shame!"),
            ("Καλή τύχη!", None, "good luck!"),
            ("Καλή επιτυχία!", None, "best of luck! much success!"),
            ("Περαστικά!", None, "get well soon!"),
            ("Χρόνια πολλά!", None, "happy birthday; many happy returns; happy name day"),
            ("Καλά Χριστούγεννα!", None, "merry Christmas"),
            ("Καλό Πάσχα!", None, "happy Easter"),
            ("Καλή Χρονιά!", None, "happy New Year"),
            ("Σιγά σιγά", None, "slowly; take it easy; don't rush"),
            ("Ήσυχα ήσυχα", None, "quietly; gently; take it easy"),
            ("Δεν έχει σημασία", None, "it doesn't matter; it's not important"),
            ("Το ίδιο μου κάνει", None, "it's all the same to me; I don't mind"),
            ("Εξαρτάται", None, "it depends"),
            ("Δεν ξέρω", None, "I don't know"),
            ("Δεν είμαι σίγουρος/η", None, "I'm not sure"),
            ("Ίσως", None, "maybe; perhaps"),
            ("Μάλλον", None, "probably; more likely"),
            ("Σίγουρα", None, "certainly; definitely; surely"),
            ("Καθόλου", None, "not at all"),
            ("Έχεις δίκιο", None, "you're right"),
            ("Δεν έχεις δίκιο", None, "you're wrong"),
            ("Συμφωνώ", None, "I agree"),
            ("Διαφωνώ", None, "I disagree"),
            ("Με νοιάζει", None, "I care; it matters to me"),
            ("Δεν με νοιάζει", None, "I don't care"),
            ("Παράξενο", None, "strange; weird; odd"),
            ("Λογικό", None, "logical; makes sense"),
            ("Κανένα πρόβλημα", None, "no problem"),
            ("Πάει αυτό", None, "that's done; it's over; forget it"),
            ("Χαλαρά", None, "easy; chill; no worries (colloquial)"),
            ("Μεγάλη υπόθεση", None, "big deal (often sarcastic)"),
            ("Δεν κάνει", None, "it won't do; it's not right"),
            ("Έγινε!", None, "done! it's done! agreed!"),
            ("Ας πούμε", None, "let's say; so to speak"),
            ("Κατά τα φαινόμενα", None, "apparently; it seems"),
            ("Βέβαια", None, "of course; certainly"),
            ("Πάντως", None, "anyway; in any case; still"),
            ("Μάλιστα", None, "indeed; yes (emphatic); I see"),
            ("Τώρα τι;", None, "now what?"),
            ("Εμπρός!", None, "forward! go ahead! come in! (on phone: hello)"),
        ],
    }),

    (39, "Γεια μας! — Social Greek & Celebrations", {
        "Ουσιαστικά": [
            ("εορτή,η", "εορτή", "celebration; feast; holiday"),
            ("γιορτή,η", "γιορτή", "holiday; celebration; name day"),
            ("Πάσχα,το", "Πάσχα", "Easter"),
            ("Χριστούγεννα,τα", "Χριστούγεννα", "Christmas"),
            ("Πρωτοχρονιά,η", "Πρωτοχρονιά", "New Year's Day"),
            ("γενέθλια,τα", "γενέθλια", "birthday"),
            ("ονομαστική εορτή,η", "ονομαστική εορτή", "name day"),
            ("γάμος,ο", "γάμος", "wedding"),
            ("βάπτιση,η", "βάπτιση", "baptism; christening"),
            ("πάρτι,το", "πάρτι", "party"),
            ("δείπνο,το", "δείπνο", "dinner (formal)"),
            ("τραπέζι,το", "τραπέζι", "table; meal (festive)"),
            ("επισκέπτης,ο", "επισκέπτης", "visitor; guest (male)"),
            ("επισκέπτρια,η", "επισκέπτρια", "visitor; guest (female)"),
            ("καλεσμένος,ο", "καλεσμένος", "invited guest"),
            ("δώρο,το", "δώρο", "gift; present"),
            ("κερί,το", "κερί", "candle; wax"),
            ("πυροτέχνημα,το", "πυροτέχνημα", "firework"),
            ("πρόποση,η", "πρόποση", "toast (raising a glass)"),
            ("χορός,ο", "χορός", "dance; dancing"),
            ("μουσική,η", "μουσική", "music"),
            ("παρέα,η", "παρέα", "company; group of friends"),
            ("διασκέδαση,η", "διασκέδαση", "fun; entertainment"),
            ("έθιμο,το", "έθιμο", "custom; tradition"),
            ("παράδοση,η", "παράδοση", "tradition"),
        ],
        "Ρήματα": [
            ("γιορτάζω", None, "to celebrate; to have a name day"),
            ("χορεύω", None, "to dance"),
            ("τραγουδώ", None, "to sing"),
            ("διασκεδάζω", None, "to have fun; to be entertained"),
            ("καλώ", None, "to invite; to call"),
            ("προσκαλώ", None, "to invite"),
            ("πίνω στην υγεία", None, "to drink to someone's health; to toast"),
            ("ευχομαι", None, "to wish; to hope"),
            ("χαιρετώ", None, "to greet"),
            ("φιλώ", None, "to kiss"),
            ("αγκαλιάζω", None, "to hug"),
        ],
        "Εκφράσεις": [
            ("Χρόνια πολλά!", None, "many years! (birthday / name day greeting)"),
            ("Να τα εκατοστίσεις!", None, "may you live to 100! (birthday wish)"),
            ("Καλή χρονιά!", None, "happy New Year!"),
            ("Καλό Πάσχα!", None, "happy Easter!"),
            ("Χριστός Ανέστη!", None, "Christ is Risen! (Easter greeting)"),
            ("Αληθώς Ανέστη!", None, "Truly He is Risen! (Easter response)"),
            ("Καλά Χριστούγεννα!", None, "merry Christmas!"),
            ("Στην υγειά σου!", None, "to your health! cheers! (informal)"),
            ("Στην υγειά μας!", None, "to our health! cheers!"),
            ("Εις υγείαν!", None, "to health! (formal toast)"),
            ("Γεια μας!", None, "cheers! (very casual)"),
            ("Κάλη όρεξη!", None, "enjoy your meal!"),
            ("Να ζήσεις!", None, "may you live long! (at celebrations)"),
            ("Να ζήσετε!", None, "may you live long! (to couple, at wedding)"),
            ("Καλωσόρισες!", None, "welcome! (informal)"),
            ("Χαίρεσαι τη ζωή σου;", None, "are you enjoying life?; you having fun?"),
            ("Περαστικά!", None, "get well soon!"),
            ("Με γεια!", None, "congratulations! (on something new e.g. new item, baby)"),
        ],
        "Επίθετα": [
            ("γιορταστικός/ή/ό", None, "festive; celebratory"),
            ("παραδοσιακός/ή/ό", None, "traditional"),
            ("σύγχρονος/η/ο", None, "modern; contemporary"),
            ("ελληνικός/ή/ό", None, "Greek"),
            ("εορταστικός/ή/ό", None, "festive; of celebration"),
            ("χαρούμενος/η/ο", None, "happy; joyful"),
            ("ξεχωριστός/ή/ό", None, "special; distinctive"),
        ],
    }),
]

def build_entries(lessons):
    entries = []
    entry_id = 10000
    for theme_id, theme_title, categories in lessons:
        pos = 1
        for category, words in categories.items():
            for word in words:
                term, lemma, english = word
                # Extract lemma and article from term if not provided
                if lemma is None:
                    # For verbs/expressions, lemma = term
                    lemma = term.split("/")[0]  # take first variant
                # Extract article from term (format "lemma,article")
                article = None
                display_term = term
                if "," in term and lemma != term:
                    parts = term.split(",", 1)
                    if len(parts) == 2:
                        display_term = parts[0]
                        article = parts[1]

                entries.append({
                    "id": entry_id,
                    "theme_id": theme_id,
                    "theme": theme_title,
                    "category": category,
                    "subsection": None,
                    "term": term,
                    "lemma": display_term,
                    "article": article,
                    "entry_source": "everyday_greek",
                    "frequency_rank": None,
                    "page": None,
                    "position_in_group": pos,
                    "form_suffixes": [],
                    "english": english,
                    "english_senses": [s.strip() for s in english.split(";")],
                    "english_source": "curated",
                    "dictionary_headword": display_term,
                    "translation_match": "exact",
                    "top5000_headword": None,
                    "top5000_rank": None,
                    "top5000_definition": None,
                    "top5000_senses": [],
                    "top5000_part_of_speech": None,
                    "top5000_notes": None,
                    "top5000_disambiguation": None,
                    "top5000_match": "unmatched",
                    "audio_filename": None,
                    "audio_path": None,
                    "audio_available": False,
                    "groupKeys": [],
                })
                entry_id += 1
                pos += 1
    return entries

def build_themes(lessons):
    themes = []
    course = "Every Day Greek"
    course_id = "every-day-greek"
    for theme_id, theme_title, categories in lessons:
        total = sum(len(v) for v in categories.values())
        translated = total  # all have english
        cats = {cat: len(words) for cat, words in categories.items()}
        themes.append({
            "id": theme_id,
            "title": theme_title,
            "entry_count": total,
            "translated_count": translated,
            "audio_count": 0,
            "categories": cats,
            "course": course,
            "courseId": course_id,
        })
    return themes

if __name__ == "__main__":
    entries = build_entries(LESSONS)
    themes = build_themes(LESSONS)

    # Fix the spicy placeholder in lesson 24
    for e in entries:
        if e["english"] == "spicy; hot" and "매운" in e["term"]:
            e["term"] = "καυτερός/ή/ό"
            e["lemma"] = "καυτερός"
            e["english"] = "spicy; hot; pungent"
            e["english_senses"] = ["spicy", "hot", "pungent"]

    out = {"themes": themes, "entries": entries}

    out_path = os.path.join(os.path.dirname(__file__), "..", "data", "everyday_greek.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    print(f"Generated {len(themes)} themes and {len(entries)} entries")
    for t in themes:
        print(f"  Lesson {t['id']}: {t['title']} — {t['entry_count']} words")
